config/routes.rb
RailsMessageBoard::Application.routes.draw do
  devise_for :users
  root "message#index"

  resources :message

end

app/models/messages.rb
class Messages < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages

  # mount mount_uploader
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :avatar
  validates_integrity_of :avatar
  validates_processing_of :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password,
      :password_confirmation, :remember_me, :avatar, :avatar_cache)
    }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :eamil, :password,
      :password_confirmation, :current_password, :avatar, :avatar_cache)
    }

  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
    def index
        # load all column
        @messages = Messages.includes(:user).all
    end

    def new

    end

    def create
        @message = Messages.new(message_params)
        @message.save
        redirect_to root_path
        #render text: params[:message].inspect
    end

    def show
        @message = Messages.find(params[:id])
    end

    def destroy
        # @message = Messages.find(params[:id])
        # @message.destroy

        Messages.destroy(params[:id])
        redirect_to message_index_path
    end

    private
        def message_params
            params.require(:message).permit(:title, :content, :author).merge(:user_id => current_user.id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMessageBoard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<%= yield %>

</body>
</html>

app/views/message/index.html.erb
<div class="hero-unit">
  <h1>Ruby On Rails</h1>
  <p>留言板系統</p>
</div>

<div class="row-fluid">
  <div class="message">
    <%= form_for :message, url: message_index_path, :html => {:class => 'form'} do |f| %>
      <%= f.hidden_field :author, :value => current_user.email if current_user %>
      <p>
        <%= f.label :標題 %><br>
        <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :留言內容 %><br>
        <%= f.text_area :content %>
      </p>

      <p>
        <%= f.submit %>
      </p>
    <% end %>
  </div>
  <ul class="unstyled" style="margin-left: 20px;">
    <% @messages.each do |message| %>
      <li style="margin-bottom:10px;">
        <%= image_tag(message.user.avatar, width: 50) %>
        <%= message.author %>
        <%= link_to message.title, message %>
        <%= link_to '刪除', message_path(message.id), method: :delete, confirm: "確定刪除？" if current_user.email == message.author if current_user %>
      </li>
    <% end %>
  </ul>
</div>